"""migracao iniii

Revision ID: 463ce7f12ba3
Revises: d45b430df006
Create Date: 2025-12-15 17:56:10.398375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '463ce7f12ba3'
down_revision: Union[str, Sequence[str], None] = 'd45b430df006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificados', sa.Column('nome_aluno', sa.String(), nullable=False))
    op.drop_column('certificados', 'aluno')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificados', sa.Column('aluno', sa.VARCHAR(), nullable=False))
    op.drop_column('certificados', 'nome_aluno')
    # ### end Alembic commands ###
